name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        run: |
          git config user.email "deploy@example.com"
          git config user.name "Deploy Bot"
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          echo "machine git.heroku.com" > ~/.netrc
          echo "login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
          echo "password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          chmod 600 ~/.netrc
          git push heroku main:main -f
