const cron = require('node-cron');
// This file contains a simple placeholder for scheduled jobs.
// It creates a demo clip in the database (if available) on a schedule.

function scheduleJobs({ sampleClips }) {
  // In development, run every minute for quick feedback; in production run at 6am daily.
  const schedule = process.env.NODE_ENV === 'development' ? '*/1 * * * *' : '0 6 * * *';

  cron.schedule(schedule, async () => {
    console.log('Cron job running - placeholder for AI clipping tasks');

    // If DB is configured, create a demo clip
    if (process.env.MONGODB_URI) {
      try {
        const Clip = require('./models/Clip');
        const demo = new Clip({
          userId: 'demo-user',
          title: `Auto clip ${new Date().toISOString()}`,
          description: 'Generated by cron placeholder',
          videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
          duration: Math.floor(Math.random() * 30) + 5,
          status: 'ready',
        });
        await demo.save();
        console.log('Saved demo clip to DB');
      } catch (err) {
        console.error('Cron: could not save demo clip:', err.message);
      }
    } else {
      console.log('Cron: no MONGODB_URI configured, skipping DB writes');
    }
  });
}

module.exports = { scheduleJobs };
