name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          HD_STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          HD_STRIPE_SUCCESS_URL: ${{ secrets.STRIPE_SUCCESS_URL }}
          HD_STRIPE_CANCEL_URL: ${{ secrets.STRIPE_CANCEL_URL }}
